import {library} from '@fortawesome/fontawesome-svg-core'

import {
    faAngleRight,
    faBold,
    faColumns,
    faDesktop,
    faEdit,
    faEllipsisH,
    faExpandArrowsAlt,
    faEye, faEyeSlash,
    faFile, faFileAlt,
    faFolder,
    faIgloo,
    faImage,
    faLink,
    faPaperclip,
    faPlus,
    faSearch,
    faSignOutAlt,
    faSlidersH,
    faStickyNote,
    faTimesCircle,
    faTrash,
    faItalic,
    faStrikethrough,
    faQuoteLeft,
    faLock,
    faKey,
    faChevronRight,
    faRedo,
    faCopy,
    faExternalLinkAlt,
    faShareAlt,
    faBug,
    faFan
} from '@fortawesome/free-solid-svg-icons'

const icons: any = [
    faImage,
    faIgloo,
    faSlidersH,
    faTrash,
    faAngleRight,
    faFolder,
    faDesktop,
    faSignOutAlt,
    faSearch,
    faEye,
    faEdit,
    faExpandArrowsAlt,
    faPlus,
    faColumns,
    faPaperclip,
    faTimesCircle,
    faStickyNote,
    faFileAlt,
    faFile,
    faEllipsisH,
    faEyeSlash,
    faLink,
    faBold,
    faItalic,
    faStrikethrough,
    faQuoteLeft,
    faLock,
    faKey,
    faChevronRight,
    faRedo,
    faCopy,
    faExternalLinkAlt,
    faShareAlt,
    faBug,
    faFan
];

library.add(...icons);
